stages:
  - build
  - security

build-frontend:
  stage: build
  tags:
    - deployx
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build

build-backend:
  stage: build
  tags:
    - deployx
  script:
    - cd server
    - node --version
    - npm --version
    - npm ci
    - npm run build

sonarqube:
  stage: security
  tags:
    - deployx
  script:
    - echo "Starting SonarQube analysis..."
    - docker run --rm --network host -e SONAR_HOST_URL="$SONAR_HOST_URL" -e SONAR_TOKEN="$SONAR_TOKEN" -v "$CI_PROJECT_DIR:/usr/src" sonarsource/sonar-scanner-cli:latest -Dsonar.projectKey=DeployX -Dsonar.projectName=DeployX -Dsonar.sources=src,server -Dsonar.exclusions=node_modules/**,dist/**,coverage/**

owasp:
  stage: security
  tags:
    - deployx
  script:
    - echo "Starting OWASP Dependency-Check..."
    - rm -rf "$CI_PROJECT_DIR/owasp-reports"
    - mkdir -p "$CI_PROJECT_DIR/owasp-reports"
    - docker run --rm -v owasp_data:/usr/share/dependency-check/data -v "$CI_PROJECT_DIR:/src" owasp/dependency-check:12.2.2 --noupdate --scan /src --project "DeployX" --format HTML --out /src/owasp-reports --exclude /src/node_modules/** --exclude /src/dist/** --exclude /src/owasp-reports/**

  artifacts:
    when: always
    paths:
      - owasp-reports/
    expire_in: 7 days
